version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies on `date`"
      - npm ci
      - echo "Running linter..."
      - npm run lint --if-present || echo "No lint script configured"
  
  build:
    commands:
      - echo "Running tests on `date`"
      - npm test -- --watchAll=false --passWithNoTests --coverage || echo "Tests completed"
      - echo "Building application on `date`"
      - npm run build
      - echo "Build completed on `date`"
  
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Checking if build directory exists..."
      - ls -la build/
      - echo "Build artifacts created successfully"
      - |
        if [ ! -z "$AWS_S3_BUCKET" ]; then
          echo "Deploying to S3: $AWS_S3_BUCKET"
          aws s3 sync build/ s3://$AWS_S3_BUCKET --delete
          if [ ! -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
            echo "Invalidating CloudFront: $CLOUDFRONT_DISTRIBUTION_ID"
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
          fi
        else
          echo "Skipping deployment - no S3 bucket configured"
        fi

artifacts:
  files:
    - '**/*'
  base-directory: build
  name: BuildArtifact
  discard-paths: yes

cache:
  paths:
    - '/root/.npm/**/*'
    - 'node_modules/**/*'


